name: questload
description: Cross-platform Meta Quest VR device manager
publish_to: 'none'

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  intl: any
  path_provider: ^2.1.5
  multicast_dns: ^0.3.3+1
  silky_scroll: ^2.6.4
  dbus: ^0.7.10
  window_manager: ^0.5.2
  flutter_acrylic: ^1.1.4
  package_info_plus: ^10.2.1
  archive: ^4.0.9
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/text.svg
    - assets/update.svg
    - assets/themes/index.json
    - assets/themes/
    - assets/headsets/
    - assets/mascot/
